// Techgrid Africa — Home & Furniture (prices in ZAR)
const PRODUCTS_HOME_FURNITURE = [
  {
    id: "mandy-4-piece-lounge-suite-brown-mandy",
    name: "Mandy 4 Piece Lounge Suite, Brown",
    brand: "Mandy",
    category: "home",
    price: 6999, rating: 3.9, reviews: 319,
    colors: ["White"],
    tag: "Top Rated",
    description: "Mandy 4 Piece Lounge Suite, Brown — comfort and style for your space from Mandy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-rossi-152cm-queen-medium-bed-set-sealy",
    name: "Sealy Rossi 152cm (Queen) Medium Bed Set",
    brand: "Sealy",
    category: "home",
    price: 9999, rating: 4.8, reviews: 636,
    colors: ["Silver"],
    description: "Sealy Rossi 152cm (Queen) Medium Bed Set — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "claudia-3-piece-daybed-black-claudia",
    name: "Claudia 3 Piece Daybed, Black",
    brand: "Claudia",
    category: "home",
    price: 7499, rating: 4.5, reviews: 665,
    colors: ["Grey"],
    description: "Claudia 3 Piece Daybed, Black — comfort and style for your space from Claudia. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-columbia-152cm-queen-firm-bed-set-standard-length-sealy",
    name: "Sealy Columbia 152cm (Queen) Firm Bed Set Standard Length",
    brand: "Sealy",
    category: "home",
    price: 7999, rating: 4.2, reviews: 682,
    colors: ["Black"],
    description: "Sealy Columbia 152cm (Queen) Firm Bed Set Standard Length — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-argo-152cm-queen-firm-bed-set-standard-length-sealy",
    name: "Sealy Argo 152cm (Queen) Firm Bed Set Standard Length",
    brand: "Sealy",
    category: "home",
    price: 6999, rating: 4.9, reviews: 181,
    colors: ["Grey"],
    description: "Sealy Argo 152cm (Queen) Firm Bed Set Standard Length — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-columbia-137cm-double-firm-bed-set-sealy",
    name: "Sealy Columbia 137cm (Double) Firm Bed Set",
    brand: "Sealy",
    category: "home",
    price: 6599, rating: 3.9, reviews: 303,
    colors: ["White"],
    tag: "New",
    description: "Sealy Columbia 137cm (Double) Firm Bed Set — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sleepmasters-brooklyn-183cm-king-firm-bed-set-standard-length-sl",
    name: "Sleepmasters Brooklyn 183cm (King) Firm Bed Set Standard Length",
    brand: "Sleepmasters",
    category: "home",
    price: 5999, compareAt: 7079, rating: 4.4, reviews: 36,
    colors: ["Silver"],
    description: "Sleepmasters Brooklyn 183cm (King) Firm Bed Set Standard Length — comfort and style for your space from Sleepmasters. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "restonic-bazaruto-152cm-queen-medium-mattress-standard-length-re",
    name: "Restonic Bazaruto 152cm (Queen) Medium Mattress Standard Length",
    brand: "Restonic",
    category: "home",
    price: 5499, compareAt: 6929, rating: 4.4, reviews: 704,
    colors: ["Silver"],
    description: "Restonic Bazaruto 152cm (Queen) Medium Mattress Standard Length — comfort and style for your space from Restonic. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "edblo-berlin-137cm-double-medium-bed-set-edblo",
    name: "Edblo Berlin 137cm (Double) Medium Bed Set",
    brand: "Edblo",
    category: "home",
    price: 4599, compareAt: 5243, rating: 4.4, reviews: 52,
    colors: ["Silver"],
    description: "Edblo Berlin 137cm (Double) Medium Bed Set — comfort and style for your space from Edblo. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-cavalli-152cm-queen-plush-bed-set-standard-length-sealy",
    name: "Sealy Cavalli 152cm (Queen) Plush Bed Set Standard Length",
    brand: "Sealy",
    category: "home",
    price: 10499, compareAt: 11969, rating: 4.4, reviews: 572,
    colors: ["Silver"],
    description: "Sealy Cavalli 152cm (Queen) Plush Bed Set Standard Length — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-argo-183cm-king-firm-bed-set-standard-length-sealy",
    name: "Sealy Argo 183cm (King) Firm Bed Set Standard Length",
    brand: "Sealy",
    category: "home",
    price: 9999, rating: 4.2, reviews: 258,
    colors: ["Black"],
    description: "Sealy Argo 183cm (King) Firm Bed Set Standard Length — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "serta-apollo-152cm-queen-firm-bed-set-standard-length-serta",
    name: "Serta Apollo 152cm (Queen) Firm Bed Set Standard Length",
    brand: "Serta",
    category: "home",
    price: 5599, compareAt: 7223, rating: 4.7, reviews: 247,
    colors: ["White"],
    tag: "Value Pick",
    description: "Serta Apollo 152cm (Queen) Firm Bed Set Standard Length — comfort and style for your space from Serta. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "edblo-berlin-152cm-queen-medium-bed-set-standard-length-edblo",
    name: "Edblo Berlin 152cm (Queen) Medium Bed Set Standard Length",
    brand: "Edblo",
    category: "home",
    price: 4999, compareAt: 5749, rating: 4.1, reviews: 673,
    colors: ["Grey"],
    description: "Edblo Berlin 152cm (Queen) Medium Bed Set Standard Length — comfort and style for your space from Edblo. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "serta-athena-137cm-double-firm-bed-set-standard-length-serta",
    name: "Serta Athena 137cm (Double) Firm Bed Set Standard Length",
    brand: "Serta",
    category: "home",
    price: 6699, rating: 4.3, reviews: 239,
    colors: ["White"],
    tag: "Top Rated",
    description: "Serta Athena 137cm (Double) Firm Bed Set Standard Length — comfort and style for your space from Serta. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "serta-avalon-152cm-queen-plush-bed-set-standard-length-serta",
    name: "Serta Avalon 152cm (Queen) Plush Bed Set Standard Length",
    brand: "Serta",
    category: "home",
    price: 11599, rating: 4.5, reviews: 129,
    colors: ["Grey"],
    description: "Serta Avalon 152cm (Queen) Plush Bed Set Standard Length — comfort and style for your space from Serta. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sleepmasters-santos-mkii-152cm-queen-plush-bed-set-standard-leng",
    name: "Sleepmasters Santos MKII 152cm (Queen) Plush Bed Set Standard Length",
    brand: "Sleepmasters",
    category: "home",
    price: 7499, rating: 4, reviews: 252,
    colors: ["Silver"],
    description: "Sleepmasters Santos MKII 152cm (Queen) Plush Bed Set Standard Length — comfort and style for your space from Sleepmasters. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sleepmasters-supreme-152cm-queen-firm-bed-set-standard-length-sl",
    name: "Sleepmasters Supreme 152cm (Queen) Firm Bed Set Standard Length",
    brand: "Sleepmasters",
    category: "home",
    price: 5999, rating: 4.2, reviews: 230,
    colors: ["Black"],
    description: "Sleepmasters Supreme 152cm (Queen) Firm Bed Set Standard Length — comfort and style for your space from Sleepmasters. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "serta-aura-152cm-queen-medium-bed-set-standard-length-serta",
    name: "Serta Aura 152cm (Queen) Medium Bed Set Standard Length",
    brand: "Serta",
    category: "home",
    price: 9499, compareAt: 11589, rating: 4.4, reviews: 60,
    colors: ["Silver"],
    description: "Serta Aura 152cm (Queen) Medium Bed Set Standard Length — comfort and style for your space from Serta. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sleepmasters-saville-mkii-152cm-queen-medium-bed-set-standard-le",
    name: "Sleepmasters Saville MKII 152cm (Queen) Medium Bed Set Standard Length",
    brand: "Sleepmasters",
    category: "home",
    price: 7499, compareAt: 9149, rating: 4.4, reviews: 180,
    colors: ["Silver"],
    description: "Sleepmasters Saville MKII 152cm (Queen) Medium Bed Set Standard Length — comfort and style for your space from Sleepmasters. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "restonic-bali-183cm-king-medium-bed-set-standard-length-restonic",
    name: "Restonic Bali 183cm (King) Medium Bed Set Standard Length",
    brand: "Restonic",
    category: "home",
    price: 9999, compareAt: 12599, rating: 4.4, reviews: 44,
    colors: ["Silver"],
    description: "Restonic Bali 183cm (King) Medium Bed Set Standard Length — comfort and style for your space from Restonic. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-ergonomic-gaming-computer-desk-carbon-steel-frame-120cm-",
    name: "TechPro Ergonomic Gaming Computer Desk Carbon Steel Frame 120cm",
    brand: "TechPro",
    category: "home",
    price: 1599, rating: 4.3, reviews: 523,
    colors: ["White"],
    tag: "New",
    description: "TechPro Ergonomic Gaming Computer Desk Carbon Steel Frame 120cm — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-argo-152cm-queen-medium-bed-set-sealy",
    name: "Sealy Argo 152cm (Queen) Medium Bed Set",
    brand: "Sealy",
    category: "home",
    price: 8999, compareAt: 10169, rating: 4.7, reviews: 631,
    colors: ["White"],
    tag: "Hot Deal",
    description: "Sealy Argo 152cm (Queen) Medium Bed Set — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sealy-rossi-137cm-double-plush-bed-set-sealy",
    name: "Sealy Rossi 137cm (Double) Plush Bed Set",
    brand: "Sealy",
    category: "home",
    price: 7499, rating: 4.9, reviews: 589,
    colors: ["Grey"],
    description: "Sealy Rossi 137cm (Double) Plush Bed Set — comfort and style for your space from Sealy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "restonic-bazaruto-152cm-queen-medium-base-set-restonic",
    name: "Restonic Bazaruto 152cm (Queen) Medium Base Set",
    brand: "Restonic",
    category: "home",
    price: 7499, rating: 4.6, reviews: 134,
    colors: ["Black"],
    description: "Restonic Bazaruto 152cm (Queen) Medium Base Set — comfort and style for your space from Restonic. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "serta-apollo-152cm-queen-firm-bed-set-serta",
    name: "Serta Apollo 152cm (Queen) Firm Bed Set",
    brand: "Serta",
    category: "home",
    price: 5599, rating: 4.6, reviews: 42,
    colors: ["Black"],
    description: "Serta Apollo 152cm (Queen) Firm Bed Set — comfort and style for your space from Serta. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "sleepmasters-brooklyn-152cm-queen-firm-bed-set-sleepmasters",
    name: "Sleepmasters Brooklyn 152cm (Queen) Firm Bed Set",
    brand: "Sleepmasters",
    category: "home",
    price: 5999, rating: 4.5, reviews: 61,
    colors: ["Grey"],
    description: "Sleepmasters Brooklyn 152cm (Queen) Firm Bed Set — comfort and style for your space from Sleepmasters. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "cozy-nights-serenity-137cm-double-firm-base-set-cozy-nights",
    name: "Cozy Nights Serenity 137cm (Double) Firm Base Set",
    brand: "Cozy Nights",
    category: "home",
    price: 3999, rating: 4.8, reviews: 276,
    colors: ["Silver"],
    description: "Cozy Nights Serenity 137cm (Double) Firm Base Set — comfort and style for your space from Cozy Nights. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "mandy-3-piece-lounge-suite-grey-mandy",
    name: "Mandy 3 Piece Lounge Suite, Grey",
    brand: "Mandy",
    category: "home",
    price: 5999, rating: 3.9, reviews: 363,
    colors: ["White"],
    tag: "New",
    description: "Mandy 3 Piece Lounge Suite, Grey — comfort and style for your space from Mandy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "mandy-recliner-lounge-chair-mandy",
    name: "Mandy Recliner Lounge Chair",
    brand: "Mandy",
    category: "home",
    price: 2999, compareAt: 3719, rating: 3.8, reviews: 502,
    colors: ["Black"],
    description: "Mandy Recliner Lounge Chair — comfort and style for your space from Mandy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "claudia-2-piece-daybed-claudia",
    name: "Claudia 2 Piece Daybed",
    brand: "Claudia",
    category: "home",
    price: 5499, compareAt: 6599, rating: 3.8, reviews: 178,
    colors: ["Black"],
    description: "Claudia 2 Piece Daybed — comfort and style for your space from Claudia. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "vegas-executive-office-chair-black-vegas",
    name: "Vegas Executive Office Chair Black",
    brand: "Vegas",
    category: "home",
    price: 1299, compareAt: 1611, rating: 3.8, reviews: 382,
    colors: ["Black"],
    description: "Vegas Executive Office Chair Black — comfort and style for your space from Vegas. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "vegas-ergonomic-mesh-office-chair-vegas",
    name: "Vegas Ergonomic Mesh Office Chair",
    brand: "Vegas",
    category: "home",
    price: 1599, rating: 4.9, reviews: 685,
    colors: ["Grey"],
    description: "Vegas Ergonomic Mesh Office Chair — comfort and style for your space from Vegas. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-computer-desk-with-drawer-100cm-techpro",
    name: "TechPro Computer Desk with Drawer 100cm",
    brand: "TechPro",
    category: "home",
    price: 1299, rating: 4.5, reviews: 545,
    colors: ["Grey"],
    description: "TechPro Computer Desk with Drawer 100cm — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-standing-desk-120cm-techpro",
    name: "TechPro Standing Desk 120cm",
    brand: "TechPro",
    category: "home",
    price: 2999, compareAt: 3509, rating: 4.7, reviews: 335,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Standing Desk 120cm — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "mandy-fabric-2-seater-couch-mandy",
    name: "Mandy Fabric 2-Seater Couch",
    brand: "Mandy",
    category: "home",
    price: 4999, compareAt: 6349, rating: 4.1, reviews: 545,
    colors: ["Grey"],
    description: "Mandy Fabric 2-Seater Couch — comfort and style for your space from Mandy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "restonic-bali-183cm-king-plush-bed-set-restonic",
    name: "Restonic Bali 183cm (King) Plush Bed Set",
    brand: "Restonic",
    category: "home",
    price: 9999, compareAt: 11399, rating: 4.4, reviews: 272,
    colors: ["Silver"],
    description: "Restonic Bali 183cm (King) Plush Bed Set — comfort and style for your space from Restonic. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "cozy-nights-pillow-pair-set-medium-cozy-nights",
    name: "Cozy Nights Pillow Pair Set (Medium)",
    brand: "Cozy Nights",
    category: "home",
    price: 499, rating: 4, reviews: 356,
    colors: ["Silver"],
    description: "Cozy Nights Pillow Pair Set (Medium) — comfort and style for your space from Cozy Nights. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-tv-stand-140cm-techpro",
    name: "TechPro TV Stand 140cm",
    brand: "TechPro",
    category: "home",
    price: 1999, rating: 4.2, reviews: 506,
    colors: ["Black"],
    description: "TechPro TV Stand 140cm — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "mandy-coffee-table-round-mandy",
    name: "Mandy Coffee Table Round",
    brand: "Mandy",
    category: "home",
    price: 1499, compareAt: 1934, rating: 4.7, reviews: 147,
    colors: ["White"],
    tag: "Value Pick",
    description: "Mandy Coffee Table Round — comfort and style for your space from Mandy. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-techpro",
    name: "TechPro Bookshelf 5-Tier",
    brand: "TechPro",
    category: "home",
    price: 1799, rating: 3.9, reviews: 595,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-techpro",
    name: "TechPro Bookshelf 5-Tier (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1745, rating: 4.8, reviews: 200,
    colors: ["Silver"],
    description: "TechPro Bookshelf 5-Tier (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-techpro",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1693, rating: 4.3, reviews: 363,
    colors: ["White"],
    tag: "New",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-techpro",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1642, rating: 4.8, reviews: 356,
    colors: ["Silver"],
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-techpro",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1593, rating: 3.9, reviews: 391,
    colors: ["White"],
    tag: "Hot Deal",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-techpro",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1545, rating: 4.8, reviews: 436,
    colors: ["Silver"],
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-tec",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1499, compareAt: 1949, rating: 4.4, reviews: 408,
    colors: ["Silver"],
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1454, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-491",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1410, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-492",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1368, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-493",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1327, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-494",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1287, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-495",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1248, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-496",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1211, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-497",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1175, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-498",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1140, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  },
  {
    id: "techpro-bookshelf-5-tier-extra-extra-extra-extra-extra-extra-ext-499",
    name: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra)",
    brand: "TechPro",
    category: "home",
    price: 1106, rating: 3.9, reviews: 175,
    colors: ["White"],
    tag: "Bestseller",
    description: "TechPro Bookshelf 5-Tier (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) (Extra) — comfort and style for your space from TechPro. Quality materials, supportive design and great value.",
    highlights: ["Free nationwide delivery over R5,000", "12-month warranty included", "30-day hassle-free returns"],
    specs: [[["Brand", "See product"], ["Warranty", "12 months"]]],
    image: "images/ph/home.svg"
  }
];
